version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13.0-stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: setup postgres
          command: |
            sudo apt-get update && sudo apt-get install -y postgresql-client
            psql -c "create user dockstore with password 'dockstore' createdb;" -U postgres
            psql -c "ALTER USER dockstore WITH superuser;" -U postgres
            psql -c 'create database webservice_test with owner = dockstore;' -U postgres
      - run: #need chrome, should be in Docker image
          command: |
            sudo curl https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - \
            && sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
            && sudo apt-get update \
            && sudo apt-get install -y google-chrome-stable build-essential jq git openssh-server \
            && sudo apt-get clean \
            && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      - run: # need java for swagger codegen
          command: |
            sudo apt-get update \
            && sudo apt-get install -y openjdk-8-jdk
      - run: # run tests
          command: |
            scripts/run-travis-script.sh
            npm run lint
            npm run test --watch=false --code-coverage --browsers ChromeHeadless
            npm run build.prod

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
